import { AppInstance, AppInstanceData, User, AppHeaderData } from '../types';

export const mockApp: AppInstance = {
  app: { app_key: 'test', platform: 'test' },
  id: 1,
  package: {
    manifest: {
      format: 1,
      license: { type: 'test', url: 'test' },
      developer: { name: 'test', identifier: 'test', authors: [] },
      application: {
        type: 'test',
        key: 'test',
        visibility: 'test',
        name: 'test',
        description: 'test',
        summary: 'test',
        category: 'test',
        website: 'test',
        segments: ['test'],
        ui: {
          initial_size: { w: 100, h: 100 },
          multi_rig: false,
          full_screen_report: false,
          use_app_header_v3: false,
        },
      },
      settings: {
        entrypoint: { file: 'test', function: 'test' },
        environment: {},
        runtime: 'test',
        app: { log_type: 'test' },
        enable_isolation: false,
      },
      datasets: {},
    },
    build: 'test',
    version: 'test',
  },
  segment: ['test'],
  settings: {},
};

export const mockUser: User = {
  id: 1,
  company_id: 1,
  first_name: 'Test',
  last_name: 'User',
  email: 'test@test.com',
  mobile: '1234567890',
  created_at: '2023-01-01',
  terms_acceptance_at: '2023-01-01',
  profile_photo: null,
  recently_viewed_asset_ids: [],
  unit_system: null,
  custom_unit_system: null,
  role: 'test',
  title: null,
  group: null,
  favorite_asset_id: null,
  current_segment: 'test',
  theme: 'test',
  messaging_id: 'test',
  restricted_assets: [],
  restricted_programs: [],
  settings: {
    favorites: [],
    home_page: { selected_assets_tab: 'test' },
    onboarded: false,
    beta_2_158: {},
    uiSettings: {},
    singleAsset: {
      padId: 1,
      rigId: 1,
      wellId: null,
      rigAssetId: 1,
      fracFleetId: 1,
      wellAssetId: null,
      drilloutUnitId: 1,
      completionWellAssetId: 1,
    },
    feed_filters: {
      company_id: null,
      start_date: '2023-01-01',
      content_types: [],
      selected_rigs_ids: [],
      selected_user_ids: [],
      users_radio_value: 'test',
      assets_radio_value: 'test',
      date_range_radio_value: 'test',
    },
    sms_blacklisted: false,
    favorit_asset_ids: [],
    restricted_assets: [],
    alerts_list_filters: {
      end_date: '2023-01-01',
      segments: [],
      alert_name: 'test',
      start_date: '2023-01-01',
      validation: 'test',
      alert_levels: [],
      subscription: 'test',
      classification: 'test',
      assets_radio_value: 'test',
      date_range_radio_value: 'test',
    },
    restricted_programs: [],
    is_dnd_feature_shown: false,
    last_new_alerts_check: '2023-01-01',
    notifications_filters: {
      end_date: '2023-01-01',
      start_date: '2023-01-01',
      content_types: [],
      date_range_radio_value: 'test',
    },
    directional_app_settings: {
      curve_to_lat_threshold: 0,
      vert_to_curve_threshold: 0,
    },
    last_new_feed_items_check: '2023-01-01',
    participates_in_beta_apps: false,
    'cross-plot__gradient-manager': [],
    last_new_dashboard_shares_check: '2023-01-01',
    formation_evaluation_lithology_types: {},
    formation_evaluation_custom_gradients: [],
  },
  last_sign_in_at: '2023-01-01',
  locked_access: false,
  unit_ids: [],
  intercom_admin_id: null,
  resource: [],
  consent_to_process_data: false,
  identity_verification_enabled: null,
  intercom_user_hash: 'test',
  impersonating: false,
  profile_groups: [],
  preference: {
    id: 1,
    push_notifications_enabled: false,
    emails_enabled: false,
    sms_enabled: false,
    alert_levels: [],
    play_alerts_sound: false,
    show_intercom_icon: false,
    segment: [],
    disable_create_dashboard: false,
    disable_costs: false,
    disable_documents: false,
    realtime_operation_mode: false,
    disable_file_upload: false,
    stay_on_app_store: false,
    new_navigation_beta: false,
    new_mobile_app_enabled: false,
  },
  company: {
    id: 1,
    name: 'Test Company',
    time_zone: 'UTC',
    language: 'en',
    provider: 'test',
    unit_system: {},
    custom_unit_system: {},
    custom_units: {},
    dev_center_enabled: false,
    with_subscription: false,
    competitor_analysis_enabled: false,
    ai_model_scope: 'test',
  },
  groups: [],
};

export const mockAppData: AppInstanceData = {
  id: 1,
  rig: null,
  well: null,
  fracFleet: null,
  program: {
    id: null,
    name: null,
  },
  wells: null,
  isLoading: false,
  appHash: 'test',
};

export const mockAppHeaderProps: AppHeaderData = {
  app: mockApp,
  appLastAnnotation: null,
  appSettings: {},
  coordinates: { w: 0, h: 0, x: 0, y: 0, pixelHeight: 0, pixelWidth: 0 },
  currentUser: mockUser,
  isMaximized: false,
  layoutEnvironment: { type: 'test', pdfReportMode: false },
};
